---
- name: Hello World
  hosts: "{{ target_host | default('127.0.0.1') }}"
  vars:
    first_string: "{{ first_string | default('Hello') }}"
    second_string: "{{ second_string | default('World') }}"
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print first string
     ansible.builtin.debug:
      msg: "{{ first_string }}"
   
   - name: Print second string
     ansible.builtin.debug:
      msg: "{{ second_string }}"
...