---
- name: Hello World
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    first_string: "Hello"
    second_string: "World"
  tasks:
   - name: Print first string
     ansible.builtin.debug:
      msg: "{{ first_string }}"
   
   - name: Print second string
     ansible.builtin.debug:
      msg: "{{ second_string }}"
...